version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8181:8181"
    environment:
      - PORT=8181

  transaction:
    build:
      context: ./transaction-service
    ports:
      - "8088:8088"
    environment:
      - PORT=8088

  prometheus:
    image: prom/prometheus
    container_name: shoestore-prometheus
    network_mode: bridge
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: always

  grafana:
    image: grafana/grafana
    container_name: shoestore-grafana
    network_mode: bridge
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    restart: always

volumes:
  mongo-data:
  prometheus_data:
  grafana_data:
