version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8181:8181"
    environment:
      - PORT=8181

  transaction:
    build:
      context: ./transaction-service
    ports:
      - "8088:8088"
    environment:
      - PORT=8088
      - REDIS_ADDR=redis:6379

  auth-service:
    build:
      context: ./auth-service
    ports:
        - "8087:8087"
    environment:
        - PORT=8087
        - REDIS_ADDR=redis:6379

  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "5052:5052"
      - "5053:5053"
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=5052
      - MONGO_CONNECT=mongodb+srv://app:wSxRgMArSwXKS9Rv@cluster.dnxyg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster

  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  prometheus:
    image: prom/prometheus
    container_name: shoestore-prometheus
    network_mode: bridge
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: always

  grafana:
    image: grafana/grafana
    container_name: shoestore-grafana
    network_mode: bridge
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.27.0
    restart: unless-stopped
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:
  redis_data:
  nats_data:
