global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
        - targets: [ "localhost:9090"]

  - job_name: "api-gateway"
    static_configs:
      - targets: ['host.docker.internal:8181']

  - job_name: 'transaction-service'
    static_configs:
      - targets: ['host.docker.internal:8088']

  - job_name: "auth-service"
    static_configs:
      - targets: ['host.docker.internal:8087']

  - job_name: "inventory-service"
    static_configs:
      - targets: ['host.docker.internal:5053']
