// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/inventory.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSneakersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "admin" or "user"
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSneakersRequest) Reset() {
	*x = GetSneakersRequest{}
	mi := &file_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSneakersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSneakersRequest) ProtoMessage() {}

func (x *GetSneakersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSneakersRequest.ProtoReflect.Descriptor instead.
func (*GetSneakersRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *GetSneakersRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetSneakersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSneakersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CreateSneakerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "admin" only
	Brand         string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSneakerRequest) Reset() {
	*x = CreateSneakerRequest{}
	mi := &file_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSneakerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSneakerRequest) ProtoMessage() {}

func (x *CreateSneakerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSneakerRequest.ProtoReflect.Descriptor instead.
func (*CreateSneakerRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSneakerRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateSneakerRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateSneakerRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateSneakerRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateSneakerRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type EditSneakerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "admin" only
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Brand         string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditSneakerRequest) Reset() {
	*x = EditSneakerRequest{}
	mi := &file_proto_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditSneakerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditSneakerRequest) ProtoMessage() {}

func (x *EditSneakerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditSneakerRequest.ProtoReflect.Descriptor instead.
func (*EditSneakerRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *EditSneakerRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *EditSneakerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditSneakerRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *EditSneakerRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EditSneakerRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *EditSneakerRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type RemoveSneakerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "admin" only
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSneakerRequest) Reset() {
	*x = RemoveSneakerRequest{}
	mi := &file_proto_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSneakerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSneakerRequest) ProtoMessage() {}

func (x *RemoveSneakerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSneakerRequest.ProtoReflect.Descriptor instead.
func (*RemoveSneakerRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveSneakerRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RemoveSneakerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPublicSneakersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicSneakersRequest) Reset() {
	*x = GetPublicSneakersRequest{}
	mi := &file_proto_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicSneakersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicSneakersRequest) ProtoMessage() {}

func (x *GetPublicSneakersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicSneakersRequest.ProtoReflect.Descriptor instead.
func (*GetPublicSneakersRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *GetPublicSneakersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPublicSneakersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SneakerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sneaker       *Sneaker               `protobuf:"bytes,1,opt,name=sneaker,proto3" json:"sneaker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SneakerResponse) Reset() {
	*x = SneakerResponse{}
	mi := &file_proto_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SneakerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SneakerResponse) ProtoMessage() {}

func (x *SneakerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SneakerResponse.ProtoReflect.Descriptor instead.
func (*SneakerResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *SneakerResponse) GetSneaker() *Sneaker {
	if x != nil {
		return x.Sneaker
	}
	return nil
}

type RemoveSneakerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSneakerResponse) Reset() {
	*x = RemoveSneakerResponse{}
	mi := &file_proto_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSneakerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSneakerResponse) ProtoMessage() {}

func (x *RemoveSneakerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSneakerResponse.ProtoReflect.Descriptor instead.
func (*RemoveSneakerResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveSneakerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSneakersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sneakers      []*Sneaker             `protobuf:"bytes,1,rep,name=sneakers,proto3" json:"sneakers,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSneakersResponse) Reset() {
	*x = GetSneakersResponse{}
	mi := &file_proto_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSneakersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSneakersResponse) ProtoMessage() {}

func (x *GetSneakersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSneakersResponse.ProtoReflect.Descriptor instead.
func (*GetSneakersResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *GetSneakersResponse) GetSneakers() []*Sneaker {
	if x != nil {
		return x.Sneakers
	}
	return nil
}

func (x *GetSneakersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetPublicSneakersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sneakers      []*Sneaker             `protobuf:"bytes,1,rep,name=sneakers,proto3" json:"sneakers,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicSneakersResponse) Reset() {
	*x = GetPublicSneakersResponse{}
	mi := &file_proto_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicSneakersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicSneakersResponse) ProtoMessage() {}

func (x *GetPublicSneakersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicSneakersResponse.ProtoReflect.Descriptor instead.
func (*GetPublicSneakersResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *GetPublicSneakersResponse) GetSneakers() []*Sneaker {
	if x != nil {
		return x.Sneakers
	}
	return nil
}

func (x *GetPublicSneakersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Sneaker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand         string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sneaker) Reset() {
	*x = Sneaker{}
	mi := &file_proto_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sneaker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sneaker) ProtoMessage() {}

func (x *Sneaker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sneaker.ProtoReflect.Descriptor instead.
func (*Sneaker) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *Sneaker) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sneaker) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Sneaker) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Sneaker) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Sneaker) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

var File_proto_inventory_proto protoreflect.FileDescriptor

const file_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"\x15proto/inventory.proto\x12\x05proto\"R\n" +
	"\x12GetSneakersRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x82\x01\n" +
	"\x14CreateSneakerRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\"\x90\x01\n" +
	"\x12EditSneakerRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\":\n" +
	"\x14RemoveSneakerRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"D\n" +
	"\x18GetPublicSneakersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\";\n" +
	"\x0fSneakerResponse\x12(\n" +
	"\asneaker\x18\x01 \x01(\v2\x0e.proto.SneakerR\asneaker\"1\n" +
	"\x15RemoveSneakerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"W\n" +
	"\x13GetSneakersResponse\x12*\n" +
	"\bsneakers\x18\x01 \x03(\v2\x0e.proto.SneakerR\bsneakers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"]\n" +
	"\x19GetPublicSneakersResponse\x12*\n" +
	"\bsneakers\x18\x01 \x03(\v2\x0e.proto.SneakerR\bsneakers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"q\n" +
	"\aSneaker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color2\x84\x03\n" +
	"\x10InventoryService\x12D\n" +
	"\vGetSneakers\x12\x19.proto.GetSneakersRequest\x1a\x1a.proto.GetSneakersResponse\x12D\n" +
	"\rCreateSneaker\x12\x1b.proto.CreateSneakerRequest\x1a\x16.proto.SneakerResponse\x12@\n" +
	"\vEditSneaker\x12\x19.proto.EditSneakerRequest\x1a\x16.proto.SneakerResponse\x12J\n" +
	"\rRemoveSneaker\x12\x1b.proto.RemoveSneakerRequest\x1a\x1c.proto.RemoveSneakerResponse\x12V\n" +
	"\x11GetPublicSneakers\x12\x1f.proto.GetPublicSneakersRequest\x1a .proto.GetPublicSneakersResponseB/Z-github.com/shoe-store/inventory-service/protob\x06proto3"

var (
	file_proto_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_proto_rawDescData []byte
)

func file_proto_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)))
	})
	return file_proto_inventory_proto_rawDescData
}

var file_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_inventory_proto_goTypes = []any{
	(*GetSneakersRequest)(nil),        // 0: proto.GetSneakersRequest
	(*CreateSneakerRequest)(nil),      // 1: proto.CreateSneakerRequest
	(*EditSneakerRequest)(nil),        // 2: proto.EditSneakerRequest
	(*RemoveSneakerRequest)(nil),      // 3: proto.RemoveSneakerRequest
	(*GetPublicSneakersRequest)(nil),  // 4: proto.GetPublicSneakersRequest
	(*SneakerResponse)(nil),           // 5: proto.SneakerResponse
	(*RemoveSneakerResponse)(nil),     // 6: proto.RemoveSneakerResponse
	(*GetSneakersResponse)(nil),       // 7: proto.GetSneakersResponse
	(*GetPublicSneakersResponse)(nil), // 8: proto.GetPublicSneakersResponse
	(*Sneaker)(nil),                   // 9: proto.Sneaker
}
var file_proto_inventory_proto_depIdxs = []int32{
	9, // 0: proto.SneakerResponse.sneaker:type_name -> proto.Sneaker
	9, // 1: proto.GetSneakersResponse.sneakers:type_name -> proto.Sneaker
	9, // 2: proto.GetPublicSneakersResponse.sneakers:type_name -> proto.Sneaker
	0, // 3: proto.InventoryService.GetSneakers:input_type -> proto.GetSneakersRequest
	1, // 4: proto.InventoryService.CreateSneaker:input_type -> proto.CreateSneakerRequest
	2, // 5: proto.InventoryService.EditSneaker:input_type -> proto.EditSneakerRequest
	3, // 6: proto.InventoryService.RemoveSneaker:input_type -> proto.RemoveSneakerRequest
	4, // 7: proto.InventoryService.GetPublicSneakers:input_type -> proto.GetPublicSneakersRequest
	7, // 8: proto.InventoryService.GetSneakers:output_type -> proto.GetSneakersResponse
	5, // 9: proto.InventoryService.CreateSneaker:output_type -> proto.SneakerResponse
	5, // 10: proto.InventoryService.EditSneaker:output_type -> proto.SneakerResponse
	6, // 11: proto.InventoryService.RemoveSneaker:output_type -> proto.RemoveSneakerResponse
	8, // 12: proto.InventoryService.GetPublicSneakers:output_type -> proto.GetPublicSneakersResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_inventory_proto_init() }
func file_proto_inventory_proto_init() {
	if File_proto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_proto_depIdxs,
		MessageInfos:      file_proto_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_proto = out.File
	file_proto_inventory_proto_goTypes = nil
	file_proto_inventory_proto_depIdxs = nil
}
