// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/inventory.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryService_GetSneakers_FullMethodName       = "/proto.InventoryService/GetSneakers"
	InventoryService_CreateSneaker_FullMethodName     = "/proto.InventoryService/CreateSneaker"
	InventoryService_EditSneaker_FullMethodName       = "/proto.InventoryService/EditSneaker"
	InventoryService_RemoveSneaker_FullMethodName     = "/proto.InventoryService/RemoveSneaker"
	InventoryService_GetPublicSneakers_FullMethodName = "/proto.InventoryService/GetPublicSneakers"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryServiceClient interface {
	GetSneakers(ctx context.Context, in *GetSneakersRequest, opts ...grpc.CallOption) (*GetSneakersResponse, error)
	CreateSneaker(ctx context.Context, in *CreateSneakerRequest, opts ...grpc.CallOption) (*SneakerResponse, error)
	EditSneaker(ctx context.Context, in *EditSneakerRequest, opts ...grpc.CallOption) (*SneakerResponse, error)
	RemoveSneaker(ctx context.Context, in *RemoveSneakerRequest, opts ...grpc.CallOption) (*RemoveSneakerResponse, error)
	GetPublicSneakers(ctx context.Context, in *GetPublicSneakersRequest, opts ...grpc.CallOption) (*GetPublicSneakersResponse, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) GetSneakers(ctx context.Context, in *GetSneakersRequest, opts ...grpc.CallOption) (*GetSneakersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSneakersResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetSneakers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) CreateSneaker(ctx context.Context, in *CreateSneakerRequest, opts ...grpc.CallOption) (*SneakerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SneakerResponse)
	err := c.cc.Invoke(ctx, InventoryService_CreateSneaker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) EditSneaker(ctx context.Context, in *EditSneakerRequest, opts ...grpc.CallOption) (*SneakerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SneakerResponse)
	err := c.cc.Invoke(ctx, InventoryService_EditSneaker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) RemoveSneaker(ctx context.Context, in *RemoveSneakerRequest, opts ...grpc.CallOption) (*RemoveSneakerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSneakerResponse)
	err := c.cc.Invoke(ctx, InventoryService_RemoveSneaker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetPublicSneakers(ctx context.Context, in *GetPublicSneakersRequest, opts ...grpc.CallOption) (*GetPublicSneakersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicSneakersResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetPublicSneakers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility.
type InventoryServiceServer interface {
	GetSneakers(context.Context, *GetSneakersRequest) (*GetSneakersResponse, error)
	CreateSneaker(context.Context, *CreateSneakerRequest) (*SneakerResponse, error)
	EditSneaker(context.Context, *EditSneakerRequest) (*SneakerResponse, error)
	RemoveSneaker(context.Context, *RemoveSneakerRequest) (*RemoveSneakerResponse, error)
	GetPublicSneakers(context.Context, *GetPublicSneakersRequest) (*GetPublicSneakersResponse, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) GetSneakers(context.Context, *GetSneakersRequest) (*GetSneakersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSneakers not implemented")
}
func (UnimplementedInventoryServiceServer) CreateSneaker(context.Context, *CreateSneakerRequest) (*SneakerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSneaker not implemented")
}
func (UnimplementedInventoryServiceServer) EditSneaker(context.Context, *EditSneakerRequest) (*SneakerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditSneaker not implemented")
}
func (UnimplementedInventoryServiceServer) RemoveSneaker(context.Context, *RemoveSneakerRequest) (*RemoveSneakerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSneaker not implemented")
}
func (UnimplementedInventoryServiceServer) GetPublicSneakers(context.Context, *GetPublicSneakersRequest) (*GetPublicSneakersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicSneakers not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}
func (UnimplementedInventoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_GetSneakers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSneakersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetSneakers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetSneakers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetSneakers(ctx, req.(*GetSneakersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_CreateSneaker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSneakerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CreateSneaker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CreateSneaker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CreateSneaker(ctx, req.(*CreateSneakerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_EditSneaker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditSneakerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).EditSneaker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_EditSneaker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).EditSneaker(ctx, req.(*EditSneakerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_RemoveSneaker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSneakerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).RemoveSneaker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_RemoveSneaker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).RemoveSneaker(ctx, req.(*RemoveSneakerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetPublicSneakers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicSneakersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetPublicSneakers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetPublicSneakers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetPublicSneakers(ctx, req.(*GetPublicSneakersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSneakers",
			Handler:    _InventoryService_GetSneakers_Handler,
		},
		{
			MethodName: "CreateSneaker",
			Handler:    _InventoryService_CreateSneaker_Handler,
		},
		{
			MethodName: "EditSneaker",
			Handler:    _InventoryService_EditSneaker_Handler,
		},
		{
			MethodName: "RemoveSneaker",
			Handler:    _InventoryService_RemoveSneaker_Handler,
		},
		{
			MethodName: "GetPublicSneakers",
			Handler:    _InventoryService_GetPublicSneakers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/inventory.proto",
}
